<?php
// SERA ABORDADO O ARRAY ASSOCIATIVO NESTA SEÇÃO

//A DIFERENÇA DELE PARA UM ARRAY COMUN É A EXISTENCIA DE UMA CHAVE E VALOR NO LUGAR DOS NUMEROS DO ARRAY INDEXADO

$cadastro = [//TODO PARAMETRO INSERIDO ENTRE ASPAS SERA CONSIDERADO COMO ARRAY POR ISSO MINHA CHAVE NOME NÃO ESTAVA ALTERANDO PQ FALTAVA OS : QUE EU COLOQUEI AO LADO
          "NOME" => "MARCOS LEVI SANTOS TEIXEIRA",
          "IDADE" => 22,
          "ESTADO" => "BAHIA",
          "CIDADE" => "São Sebastião Do Passe"];

//print_r($array);
//NESTE EXEMPLO TEMOS UMA MATRIZ QUE NADA MAIS E QUE UM ARRAY ASSOCIATIVO COM MAIS DE UMA DIMENÇÃO

//ADICIONANDO OU ATUALIZANDO O VALOR DE UM ARRAY

$cadastro["NOME"] = "ANTONIO RAIMUNDO CIRQUEIRA TEIXEIRA";
$cadastro["IDADE"] = 65;
//print_r($array);
var_dump($cadastro);


echo "<hr>";
//REMOVENDO VALORES DE UM ARRAY USANDO A FUNÇÃO UNSET

//unset($cadastro["NOME"], $cadastro["CIDADE"]);

//array_pop($cadastro);// REMOVE O ULTIMO INTEM DE UM ARRAY

array_shift($cadastro);//REMOVE O PRIMEIRO INTEM DE UM ARRAY

print_r($cadastro);